# .gitpod.yml
tasks:
  - name: Install dependencies
    before: |
      echo `gp url` >> before.txt
      npm install
      gp sync-done install
  - name: In workspace
    command: |
      echo `gp url` >> command.txt
      gp sync-await install
      npm start
