# .gitpod.yml
tasks:
  - name: Install dependencies
    init: |
      echo `gp url` >> init.txt
      npm install
      gp sync-done install
    command: |
      echo `gp url` >> command.txt
      gp sync-await install
      npm start

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: false
    addCheck: true
    addComment: false
    addBadge: false